### PR TITLE
BigDecimal implementation fixes

### PR DESCRIPTION
**Pull request by jandrad**
I noticed there was an attempt to fix the calculations on WAX. This PR will just use bigdecimal when necessary and rely on BN otherwise. It also updates the input data for WAX and adjusts the expected value.

### CODE REVIEW

**Comment by aaroncox** [comment]
Awesome, its very appreciated!

I'll try to find some time soon to give this a spin and see how it performs. Originally when the PR was being created it was right as powerup launched, which I think was causing a lot of oddities as the system was still adjusting from its launch (I think, my memory on how powerup deployments work is fuzzy).

**Comment by Avm07** [comment]
@aaroncox Please review and merge, WAX currently does not have lib for powerup

**Comment by aaroncox** [comment]
~Merging this into a new branch to resolve some typescript issues. Then I'll validate the changes and merge into the `bigdecimal` branch.~

Ok it was my node_modules being screwed up - no typescript issues. Reviewing now.

**Comment by aaroncox** [comment]
This is published under the `next` tag on npm as `@wharfkit/resources` version `1.2.2-rc3`. 

So far it looks good, but I want to do some integration tests before publishing as `1.2.2` on the `latest` release.

**Pull request merged**
